name: mern github cicd

on: push

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - uses:  actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            -   name: Install depensencies  
                run: |
                 npm install
                env:
                    CI: true


    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: JorgeLNJunior/render-deploy@v1.4.5
              with:
                api_key: ${{secrets.RENDER_API_KEY}}
                service_id: ${{ secrets.RENDER_NEWSERVICE_ID }}
