name: MERN GitHub CI/CD

on:
  push:
    branches:
      - main

env:
  # Make these available in every job
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
  RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
  VERCEL_TOKEN:    ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID:   ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Backend install & test (add your test step here if you want)
      - name: Install Backend Dependencies
        
        working-directory: ./backend
        run: npm install
        env:
          CI: true

      # Frontend install & test
      - name: Install Frontend Dependencies
       
        working-directory: ./frontend
        run: npm install
        env:
          CI: true

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Backend to Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          api_key:    ${{ env.RENDER_API_KEY }}
          service_id: ${{ env.RENDER_SERVICE_ID }}

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Settings
        run: vercel pull --yes --token=${VERCEL_TOKEN}

      - name: Build Locally
        run: vercel build --prod --yes --token=${VERCEL_TOKEN}

      - name: Deploy Prebuilt
        run: vercel deploy --prebuilt --prod --confirm --token=${VERCEL_TOKEN}
