name: mern github cicd

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
        # Install backend dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install
        env:
          CI: true

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          api_key: ${{secrets.RENDER_API_KEY}}
          service_id: ${{ secrets.RENDER_SERVICE_ID }}

  frontend_deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Install Vercel CLI
    #     run: npm install -g vercel@33.4.1
    #   - name: Deploy to Vercel
    #     uses: amondnet/vercel-action@v25
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install -g vercel@33.4.1

      - name: Build locally
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy prebuilt
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN